#!/bin/bash

if [[ ( -f "/etc/apache2/ssl/https.key" ) || ( -f "/etc/apache2/ssl/https.crt" ) ]]; then
  echo "Certificate already exists. Won't overwrite /etc/apache2/ssl/https.[key|crt]!";
  exit 1
else
  openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/https.key -out /etc/apache2/ssl/https.crt
fi
